# Generated by Django 4.2.7 on 2023-11-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sniffer',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
