# Generated by Django 4.2.7 on 2023-11-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_sniffer_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sniffer',
            name='ip',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
